### PR TITLE
Update deprecated 'compile' call in gradle.build

### PR DESCRIPTION
**Pull request by corlissc**
Utilize 'implementation' vice 'compile' in gradle.build so the Gradle build won't fail.

### CODE REVIEW

**Review by affansk — APPROVED** [review]

**Comment by AlixH** [comment]
Please merge this !

**Review by Thanhal-P-A — APPROVED** [review]

**Comment by humodev** [comment]
Please, again, merge this!!!

**Comment by santiagogarzon** [comment]
Please merge this. We need it.

**Review by AlexisFabianCarranza — APPROVED** [review]

**Comment by AlexisFabianCarranza** [comment]
We need this! Pls

**Review by talut — APPROVED** [review]

**Pull request merged**
